### create job
POST http://183.66.65.207:38080/api/pipeline
Content-Type: application/json

{
  "name": "test6",
  "yaml": "version: 1.0\nname: my-test2\nstages:\n  git-clone:\n    steps:\n      - name: git-clone\n        uses: git-checkout\n        with:\n          url: https://gitee.com/mohaijiang/spring-boot-example.git\n          branch: master\n  code-compile:\n    needs:\n      - git-clone\n    steps:\n      - name: code-compile\n        runs-on: maven:3.5-jdk-8\n        run: |\n          mvn clean package -Dmaven.test.skip=true\n      - name: save artifactory\n        use: hamster-artifactory\n        with:\n          name: some.zip\n          path: target/*.jar\n  build-image:\n    needs:\n      - code-compile\n    steps:\n      - run: |\n          docker build -t mohaijiang/spring-boot-example:latest .\n"
}

### update pipeline job
PUT http://localhost:8080/pipeline/test3?oldName=test3
Content-Type: application/json

{
  "newName": "test2",
  "yaml": "version: \"1.0\"\nname: test2\nstages:\n  git-clone:\n    steps:\n      - name: git-clone\n        uses: git-checkout\n        with:\n          url: https://gitee.com/mohaijiang/spring-boot-example.git\n          branch: master"
}

### exec job
POST http://183.66.65.207:38080/api/pipeline/test2/exec
Content-Type: application/json

### re exec job
POST http://localhost:8080/api/pipeline/maven/7/re-exec

### get pipeline job
GET http://localhost:8080/pipeline/test3

### delete pipeline job
DELETE http://localhost:8080/pipeline/test2

### get pipeline job details
GET http://localhost:8080/pipeline/test2/details?page=1&size=10


### get pipeline job detail
GET http://localhost:8080/pipeline/test2/detail/0


### get pipelie job log
GET http://localhost:8080/pipeline/test2/logs/0

### delete pipelie detail
DELETE http://localhost:8080/pipeline/test2/detail/0

### exec job
POST http://localhost:8080/pipeline/test3/exec
Content-Type: application/json

### cancel job
POST http://localhost:8080/pipeline/test3/7/stop

###
GET http://localhost:8080/pipeline/test3/logs/9

###
GET http://localhost:8080/api/pipeline/template/4



###
POST http://hamsternet.io/docs/abcd1234
Content-Type: application/json

{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}
